### ISSUE TITLE
May I add mruby-io to mruby/mrbgem?

### ISSUE THREAD

**Issue by matz** [iij/mruby-io#95]
It seems to be better maintained with the core. May I?

**Comment by tsahara** [comment]
I have some questions:

- Do you want us to change the name of copyright holder?  (The reason why I ask this is because you can merge mruby-io into mruby without our permission as long as you obey the license terms of mruby-io.)
- May I have access to mruby repository to review/commit changes to imported mruby-io mrbgem?
- mruby-io has a lot of `#ifdef`s to support different platforms (*BSD/Linux/macOS/Win32,64).  Do you introduce some new compilation flags to `mrbconf.h`, configure scripts, or CMakeFiles?

**Comment by matz** [comment]
* No. I don't think it's mandatory but I wanted to ask you first to show respect.
* I will give you permissions. I don't want to take your authority away from you.
* We can. I don't have concrete ideas yet.

**Comment by tsahara** [comment]
Thank you for asking it first.  We are pleased to contribute our code to mruby core.  If you need our  help, for example, making a pull-request to import mruby-io into mruby/mruby or transfering ownership of this repository to "mruby" organization, feel free to ask us.

**Comment by tsahara** [comment]
Note about license: we IIJ are already listed on AUTHORS in mruby repository so we can remove license terms in README.md of this repository if you import mruby-io into mruby/mruby repository.

**Comment by matz** [comment]
I have imported mruby-io, mruby-socket, and mruby-pack to the repository. I have added @tsahara to the mruby contributors (invite sent). If anything we need to do, feel free to ask us.

**Comment by tsahara** [comment]
I've joined mruby org.  Thank you.

**Comment by matz** [comment]
I've updated imported gems to be compiled on WIndows (AppVeyor). Unfortunately tests still fail.
We need more updates or to disable tests on Windows.
